<?php

/**
 * @file
 * Test module for testing the entity access system.
 *
 * This module's functionality depends on the following state variables:
 * - entity_access_test.no_access_uid: Used in NodeQueryAlterTest to enable the
 *   entity_access_all grant realm.
 * - entity_access_test.private: When TRUE, the module controls access for entitys
 *   with a 'private' property set, and inherits the default core access for
 *   entitys without this flag. When FALSE, the module controls access for all
 *   entitys.
 * - entity_access_test_secret_catalan: When set to TRUE and using the Catalan
 *   'ca' language code, makes all Catalan content secret.
 *
 * @see entity_access_test_entity_grants()
 * @see \Drupal\entity\Tests\NodeQueryAlterTest
 * @see \Drupal\entity\Tests\NodeAccessBaseTableTest
 */

use Drupal\Core\Access\AccessResult;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;
use Drupal\entity\NodeTypeInterface;
use Drupal\entity\NodeInterface;

/**
 * Implements hook_entity_grants().
 *
 * Provides three grant realms:
 * - entity_access_test_author: Grants users view, update, and delete privileges
 *   on entitys they have authored. Users receive a group ID matching their user
 *   ID on this realm.
 * - entity_access_test: Grants users view privileges when they have the
 *   'entity test view' permission. Users with this permission receive two group
 *   IDs for the realm, 8888 and 8889. Access for both realms is identical;
 *   the second group is added so that the interaction of multiple groups on
 *   a given grant realm can be tested in NodeAccessPagerTest.
 * - entity_access_all: Provides grants for the user whose user ID matches the
 *   'entity_access_test.no_access_uid' state variable. Access control on this
 *   realm is not provided in this module; instead,
 *   NodeQueryAlterTest::testNodeQueryAlterOverride() manually writes a entity
 *   access record defining the access control for this realm.
 *
 * @see \Drupal\entity\Tests\NodeQueryAlterTest::testNodeQueryAlterOverride()
 * @see \Drupal\entity\Tests\NodeAccessPagerTest
 * @see entity_access_test.permissions.yml
 * @see entity_access_test_entity_access_records()
 */
function entity_access_test_entity_grants($account, $op) {
  $grants = array();
  $grants['entity_access_test_author'] = array($account->id());
  if ($op == 'view' && $account->hasPermission('entity test view', $account)) {
    $grants['entity_access_test'] = array(8888, 8889);
  }

  $no_access_uid = \Drupal::state()->get('entity_access_test.no_access_uid') ?: 0;
  if ($op == 'view' && $account->id() == $no_access_uid) {
    $grants['entity_access_all'] = array(0);
  }
  return $grants;
}

/**
 * Implements hook_entity_access_records().
 *
 * By default, records are written for all entitys. When the
 * 'entity_access_test.private' state variable is set to TRUE, records
 * are only written for entitys with a "private" property set, which causes the
 * Node module to write the default global view grant for entitys that are not
 * marked private.
 *
 * @see \Drupal\entity\Tests\NodeAccessBaseTableTest::setUp()
 * @see entity_access_test_entity_grants()
 * @see entity_access_test.permissions.yml
 */
function entity_access_test_entity_access_records(NodeInterface $entity) {
  $grants = array();
  // For NodeAccessBaseTableTestCase, only set records for private entitys.
  if (!\Drupal::state()->get('entity_access_test.private') || $entity->private->value) {
    // Groups 8888 and 8889 for the entity_access_test realm both receive a view
    // grant for all controlled entitys. See entity_access_test_entity_grants().
    $grants[] = array(
      'realm' => 'entity_access_test',
      'gid' => 8888,
      'grant_view' => 1,
      'grant_update' => 0,
      'grant_delete' => 0,
      'priority' => 0,
    );
    $grants[] = array(
      'realm' => 'entity_access_test',
      'gid' => 8889,
      'grant_view' => 1,
      'grant_update' => 0,
      'grant_delete' => 0,
      'priority' => 0,
    );
    // For the author realm, the group ID is equivalent to a user ID, which
    // means there are many many groups of just 1 user.
    $grants[] = array(
      'realm' => 'entity_access_test_author',
      'gid' => $entity->getOwnerId(),
      'grant_view' => 1,
      'grant_update' => 1,
      'grant_delete' => 1,
      'priority' => 0,
    );
  }

  return $grants;
}

/**
 * Adds the private field to a entity type.
 *
 * @param \Drupal\entity\NodeTypeInterface $type
 *   A entity type entity.
 */
function entity_access_test_add_field(NodeTypeInterface $type) {
  $field_storage = FieldStorageConfig::create(array(
    'field_name' => 'private',
    'entity_type' => 'entity',
    'type' => 'integer',
  ));
  $field_storage->save();
  $field = FieldConfig::create(array(
    'field_name' => 'private',
    'entity_type' => 'entity',
    'bundle' => $type->id(),
    'label' => 'Private',
  ));
  $field->save();

  // Assign widget settings for the 'default' form mode.
  entity_get_form_display('entity', $type->id(), 'default')
    ->setComponent('private', array(
      'type' => 'number',
    ))
    ->save();
}

/**
 * Implements hook_entity_access().
 */
function entity_access_test_entity_access(\Drupal\entity\NodeInterface $entity, $op, \Drupal\Core\Session\AccountInterface $account, $langcode) {
  $secret_catalan = \Drupal::state()
    ->get('entity_access_test_secret_catalan') ?: 0;
  if ($secret_catalan && $langcode == 'ca') {
    // Make all Catalan content secret.
    return AccessResult::forbidden()->setCacheMaxAge(0);
  }
  // No opinion.
  return AccessResult::neutral()->setCacheMaxAge(0);
}
